"""теорія: TheoryTopic, TheoryBlock, UserTheoryProgress_2_2

Revision ID: 060d1609648e
Revises: 5689d6d51e7c
Create Date: 2026-08-16 13:29:43.119080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060d1609648e'
down_revision = '5689d6d51e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theory_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theory_resources')
    # ### end Alembic commands ###
