"""category_label and issue_type_label

Revision ID: 0e2d2c54a245
Revises: 4c9a08ac9b95
Create Date: 2026-08-07 09:44:10.849337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2d2c54a245'
down_revision = '4c9a08ac9b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('issue_type_label', sa.String(length=150), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('issue_type_label')
        batch_op.drop_column('category_label')

    # ### end Alembic commands ###
