"""allowed_to_show

Revision ID: 895408fee62c
Revises: 7716af9f055d
Create Date: 2026-08-01 00:28:18.594076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895408fee62c'
down_revision = '7716af9f055d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('allowed_to_show',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('allowed_to_show',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
