"""daily tasks

Revision ID: 95db1025253a
Revises: 33cb013ece37
Create Date: 2026-08-14 17:09:58.365939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '95db1025253a'
down_revision = '33cb013ece37'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    # Створюємо таблицю тільки якщо її ще НЕМАЄ
    if 'daily_task_templates' not in tables:
        op.create_table(
            'daily_task_templates',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('key', sa.String(length=50), nullable=False),
            sa.Column('title_uk', sa.String(length=200), nullable=False),
            sa.Column('title_de', sa.String(length=200), nullable=False),
            sa.Column('title_en', sa.String(length=200), nullable=False),
            sa.Column('icon', sa.String(length=10), nullable=True),
            sa.Column('task_type', sa.String(length=30), nullable=False),
            sa.Column('target_value', sa.Integer(), nullable=True),
            sa.Column('extra_param', sa.String(length=50), nullable=True),
            sa.Column('xp_reward', sa.Integer(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('key')
        )
    # 2. Створюємо user_daily_tasks, якщо її ще немає (саме тут падає деплой)
    if 'user_daily_tasks' not in tables:
        op.create_table(
            'user_daily_tasks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('template_id', sa.Integer(), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('progress', sa.Integer(), nullable=True),
            sa.Column('is_completed', sa.Boolean(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('xp_claimed', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['template_id'], ['daily_task_templates.id']),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'template_id', 'date', name='unique_user_task_per_day')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_daily_tasks')
    op.drop_table('daily_task_templates')
    # ### end Alembic commands ###
